on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: medcheksdevacr.azurecr.io
        username: ${{ secrets.acr_medcheksdevacr_username }}
        password: ${{ secrets.acr_medcheksdevacr_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t medcheksdevacr.azurecr.io/medcheks:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push medcheksdevacr.azurecr.io/medcheks:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_medcheks_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep testshaji | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace testshaji`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: testshaji
        container-registry-url: medcheksdevacr.azurecr.io
        container-registry-username: ${{ secrets.acr_medcheksdevacr_username }}
        container-registry-password: ${{ secrets.acr_medcheksdevacr_password }}
        secret-name: medcheksdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: testshaji
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
          manifests/ingress.yml
        images: |
          medcheksdevacr.azurecr.io/medcheks:${{ github.sha }}
        imagepullsecrets: |
          medcheksdockerauth
